### ISSUE TITLE
建议conn.py,执行事务操作的时候，加上try/except

### ISSUE THREAD

**Issue by Jzone** [OxOOo/ProxyPoolWithUI#1]
很高兴能使用这个开源代码，带有ui，选型了4个，第一个就能跑起来，就打算用起来。
然而因为多线程竞争资源的原因，sqlit3事务事件，数据库锁死，就会出现错误导致程序奔溃退出。
sqlite3我用得也不多。建议如下，既可以同时，也可以选择一个。
1.要么参考https://stackoverflow.com/questions/15856976/transactions-with-python-sqlite3        （答案第1个不过是py2)，进行事务处理设置 isolation_level,可能要去掉显式事务语句 https://docs.python.org/3/library/sqlite3.html#sqlite3-controlling-transactions 
    (py3)
2.要么建议try/except
```
    c = conn.cursor()
    success = False
    count  = 0
    while not success and count < 5:
        try:
            <sql code>
            success = True
        except:
            <error process code>
            count = count + 1
            time.sleep(3)
```
自己已经改了下面，不算太官方，毕竟参考其他代码，都是偏设置，所以等待时间，重复次数，我自己偏懒惰，就随意能跑起来就可以了。

**Comment by OxOOo** [comment]
这个项目终于有人提issue了，感动~

上这个项目在开发的过程中，考虑到sqlite3只需要操作本地文件，出现错误的概率比较小，因此并没有使用try/catch优化。

而实际运行中，这个项目卡死更多是因为爬取器和验证器由于某些原因卡死了。

当然，添加try/catch也是非常有用的，后续可能会考虑添加。
