### ISSUE TITLE
代理池验证逻辑可否加快

### ISSUE THREAD

**Issue by wuheming** [OxOOo/ProxyPoolWithUI#12]
这边有很多免费代理源，都是GitHub别人分享过来的，基本每分钟更新一次，并区分了协议，自建的代理池每次能获取到3W的代理，但是我自己验证之后仅有几十个存留，请问下验证逻辑有什么要求嘛
代理源：
    url = "http://api.89ip.cn/tqdl.html?api=1&num=9999&port=&address=&isp="
    url = "http://www.proxylists.net/http_highanon.txt"
    url = "https://spys.me/proxy.txt"
    url = "http://proxysearcher.sourceforge.net/Proxy%20List.php?type=http"
    url = "http://ab57.ru/downloads/proxylist.txt"
    url = "http://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"
    url = "http://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"
    url = "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt"
    url = "https://multiproxy.org/txt_all/proxy.txt" 
    url = "http://pubproxy.com/api/proxy?limit=9999&format=txt&type=socks5"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt"
    url = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt"
    url = "https://raw.githubusercontent.com/serg-yalosovetsky/proxy/master/all_proxy.txt"
    url = "https://free-proxy-list.net"
    url = "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt"
    url = "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt"
    url = "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt"
    url = "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt"
    url = "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt"
    url = "https://raw.githubusercontent.com/proxiesmaster/Free-Proxy-List/main/proxies.txt"
    url = "https://sunny9577.github.io/proxy-scraper/proxies.txt"
这些能添加进去吗，有一些没有标明协议。或者教我下怎么添加，然后加快验证速度

**Comment by Crazy-FuQing** [comment]
你好 代理源能分享下吗  [issues ](https://github.com/OxOOo/ProxyPoolWithUI/issues/38)

**Comment by Crazy-FuQing** [comment]
@wuheming
