### ISSUE TITLE
关于run_validator中main函数的效率问题

### ISSUE THREAD

**Issue by HackerYunen** [OxOOo/ProxyPoolWithUI#16]
File: db/conn.py, line 116
```
time.sleep(0.1) # 为了解决并发读写饿死的问题
```
不太明白此处sleep的意义。

此函数在proc/run_validator.py 的main函数进行循环调用，但此处的调用仅为单线程调用。
且通过测试发现此处的sleep验证影响了out_que队列的清空，导致整个系统效率的降低。

我尝试将此功能改成独立的进程调用，但是发现sqlite只允许单线程调用，此处的代码存在优化的空间有待解决。

**Comment by OxOOo** [comment]
已经修改了。
