### ISSUE TITLE
程序在后台运行后，无法杀死进程

### ISSUE THREAD

**Issue by Chuck-Xu** [OxOOo/ProxyPoolWithUI#17]
程序用nohup命令运行后，不能杀死进程，只能通过重启服务器来杀死，希望能够改善

**Comment by OxOOo** [comment]
能否提供使用nohup启动的完整命令，和杀死进程的完整命令？

**Comment by OxOOo** [comment]
运行`python3 main.py`之后，项目会启动3个子进程，分别是代理爬取进程，代理验证进程和网页服务器进程，所以如果你运行`kill -9 pid`所指定的pid并不是`python3 main.py`的pid的话，那么就只是关闭了3个自进程中的某一个。

你可以使用`killall python3`命令来关闭，不过需要注意，**这个命令会杀死你所启动的所有python3进程**。

**Comment by Sky-Bridge** [comment]
我也遇到这问题了，后来找到方法，先过滤5000端口，找到pid，使用cat /proc/{PID}/status  查看PPID，然后先 kill PPID，再kill pid，就可以了
