### ISSUE TITLE
循环提示timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by ensucc** [OxOOo/ProxyPoolWithUI#22]
开始运行正常，过几个小时页面就开始循环提示：

网络错误
timeout of 10000ms exceeded

请问如何处理？
感谢。

**Comment by HackerYunen** [comment]
请补充更多信息，如完整的报错信息等

**Comment by HackerYunen** [comment]
看起来是 validate_once 争取不到 sqlite 的 并发锁，导致超时
可能的原因：
1、爬取器同一时间内爬的数量太多（目前的爬取器写入操作为单项写入）
2、验证器的并发线程数量过多

**Comment by ensucc** [comment]
那个，求问我现在如何操作？实在不太懂

感谢回复。

**Comment by ensucc** [comment]
重新看了下您写的介绍，很抱歉当时没有仔细看，已经找到方法，多有打扰。

祝工作生活顺利。

**Comment by PandyYang** [comment]
请问咋解决的, docker部署的时候, 过几个小时也不行了, 线程数量降低么

**Comment by OxOOo** [comment]
最新版本代码已解决
