### ISSUE TITLE
爬取器应支持在项目部署运行后能够动态新增

### ISSUE THREAD

**Issue by HackerYunen** [OxOOo/ProxyPoolWithUI#5]
我注意到，目前的爬取器都需要在fetchers/__init__.py下进行相关的实例化操作，若需要新增爬取器，则需要将项目停止部署。对于Docker部署来说，还需要重新build镜像（虽然可以通过volume进行挂载，但是我个人是不推荐这样做的），所以我认为有必要支持在项目能够直接在web端添加爬取器。
我这里提供我的一些想法：
+ 爬取器的相关注册信息应保存在db数据库中
+ 爬取器提供读取数据库再进行相关的实例化操作（可通过eval函数进行Fetcher的动态import，eval属于危险操作，可考虑给web端增加OAuth等，进行相关的权限校验，否则会危害主机自身的安全）

**Comment by OxOOo** [comment]
目前可以在运行过程中，动态开启和关闭每个爬取器的运行，可以在 http://chenyu0x00.com:8888/web/fetchers 看到每个爬取器后面有一个开关。
相关代码在proc/run_fetcher.py的58行找到。

另外，我认为增加爬取器是一个罕见操作(总不可能每天增加几十个爬取器吧)，并且使用docker调试时更推荐将代码挂载到docker中，而不是使用ADD命令。

**Comment by HackerYunen** [comment]
> 目前可以在运行过程中，动态开启和关闭每个爬取器的运行，可以在 http://chenyu0x00.com:8888/web/fetchers 看到每个爬取器后面有一个开关。
> 相关代码在proc/run_fetcher.py的58行找到。
> 
> 另外，我认为增加爬取器是一个罕见操作(总不可能每天增加几十个爬取器吧)，并且使用docker调试时更推荐将代码挂载到docker中，而不是使用ADD命令。

即使使用的是 volume 进行挂载，在新增爬取器的时候仍然无法进行动态加载，并且我认为使用 volume 易造成部署环境被污染。我昨晚将项目部署在US的某台服务器上跑了一晚上，发现有几个内置的爬取器几乎无法获取到任何代理信息（貌似是因为网站屏蔽了海外IP），仅获取到了http、sock4、socks5，并无https相关代理信息，而我恰好最需要的就是https... 当我尝试新增爬取器的时候，发现需要重新部署docker，故而提出相关issue来讨论是否有必要支持爬取器的动态新增

**Comment by OxOOo** [comment]
我不太理解动态加载新增爬取器的必要性，因为我始终认为增加爬取器是一个罕见操作。
而如果是为了调试的话，使用volume会更加方便。

另外，你需要确认你需要的是“**可以访问HTTPS网站的代理**”还是"**代理本身使用HTTPS协议**"。
如果是前者，那么http,socks4,socks5都可以做到，你只需要将config.py中的`VALIDATE_URL`设置为一个HTTPS地址就行（比如`https://www.baidu.com`）。
如果是后者，实际上目前我还没有见过这样的代理，如果有的话欢迎你给我提供一个示例。

关于如何通过HTTP代理访问HTTPS网站，可以查看文章：
https://zhuanlan.zhihu.com/p/349028243
