### ISSUE TITLE
大佬 可否加上自动配置本地代理 并设置检测时间 如果失效自动更换

### ISSUE THREAD

**Issue by koidnqewiu** [OxOOo/ProxyPoolWithUI#8]

**Comment by OxOOo** [comment]
能否再具体点？比如描述一下使用场景。

**Comment by koidnqewiu** [comment]
> 
> 
> 能否再具体点？比如描述一下使用场景。

就是自动配置代理池里存活的代理ip  如果配置的代理ip失效 自动更换新的存活代理ip

**Comment by OxOOo** [comment]
> > 能否再具体点？比如描述一下使用场景。
> 
> 就是自动配置代理池里存活的代理ip 如果配置的代理ip失效 自动更换新的存活代理ip

抱歉，我还是不太理解你的问题。什么叫“自动配置代理池里存活的代理ip”？目前代理池可以会自动定时对代理进行检测，保证代理池里面的代理都是可用的。另外“自动更换新的存活代理ip”是什么意思？

**Comment by koidnqewiu** [comment]
> 
> 
> > > 能否再具体点？比如描述一下使用场景。
> > 
> > 
> > 就是自动配置代理池里存活的代理ip 如果配置的代理ip失效 自动更换新的存活代理ip
> 
> 抱歉，我还是不太理解你的问题。什么叫“自动配置代理池里存活的代理ip”？目前代理池可以会自动定时对代理进行检测，保证代理池里面的代理都是可用的。另外“自动更换新的存活代理ip”是什么意思？

就是 调度代理池里的ip  配置本地电脑vpn代理服务 并检测如果失效 就更换代理ip

**Comment by koidnqewiu** [comment]
调度代理池里的ip 然后配置到本地电脑vpn代理服务  并检测如果失效 就更换代理ip

**Comment by OxOOo** [comment]
我大概知道你想要的功能是什么了

**Comment by HackerYunen** [comment]
这个功能感觉比较另类+小众... 
感觉还是issuer自行实现得比较好

**Comment by OxOOo** [comment]
> 这个功能感觉比较另类+小众...
> 感觉还是issuer自行实现得比较好

我倒是觉得这个功能在某些情况下还挺好用的。

我目前遇到的问题一个是目前代理池支持的代理协议很多，未来可能还会添加更多，因此如何兼容不同代理协议是一个问题。
另外，在兼容性方面也有点困难：如果借助外部程序，那么对外部程序的兼容性要求较高。如果本项目自行实现一个中间层，那么如何实现也是一个问题，比如使用epoll能够使获得很好的性能，但是在windows上兼容性存在一些问题。

目前，我没有解决上面问题之前还不打算添加这个功能。

**Comment by OxOOo** [comment]
抱歉了，这个需要暂时不太好实现，因此先关闭这个issue了。

**Comment by Crazy-FuQing** [comment]
proxifier代理链 加python自动生成ppx文件大概可以实现此功能
