### ISSUE TITLE
开心代理挺好用

### ISSUE THREAD

**Issue by Zealot666** [OxOOo/ProxyPoolWithUI#9]
import logging
import re

import requests
from pyquery import PyQuery as pq

from .BaseFetcher import BaseFetcher

class KxdailiFetcher(BaseFetcher):
    """
    http://www.kxdaili.com/dailiip/1/{page}.html
    """

    def fetch(self):
        """
        执行一次爬取，返回一个数组，每个元素是(protocol, ip, port)，portocol是协议名称，目前主要为http
        返回示例：[('http', '127.0.0.1', 8080), ('http', '127.0.0.1', 1234)]
        """

        ip_regex = re.compile(r'^\d+\.\d+\.\d+\.\d+$')
        port_regex = re.compile(r'^\d+$')
        proxies = []
        urls = []
        urls = urls + [f'http://www.kxdaili.com/dailiip/1/{page}.html' for page in range(1, 11)]
        urls = urls + [f'http://www.kxdaili.com/dailiip/2/{page}.html' for page in range(1, 11)]

        for url in urls:
            html = requests.get(url, timeout=10)
            html.encoding = 'utf-8'
            doc = pq(html.text)
            for line in doc('tr').items():
                tds = list(line('td').items())
                if len(tds) >= 2:
                    ip = tds[0].text().strip()
                    port = tds[1].text().strip()
                    if re.match(ip_regex, ip) is not None and re.match(port_regex, port) is not None:
                        proxies.append(('http', ip, int(port)))

        return list(set(proxies))

**Comment by Zealot666** [comment]
<img width="826" alt="Snipaste_2021-06-30_15-44-55" src="https://user-images.githubusercontent.com/31880714/123921960-23a39680-d9ba-11eb-9f6e-ae273e4f5398.png">

**Comment by OxOOo** [comment]
看起来很不错，麻烦你提交一个Pull Request~
